### ISSUE TITLE
config.env shouldn't be online

### ISSUE THREAD

**Issue by jsms90** [pbywater/week6-zapo#40]
This should be added to your gitignore

In order to get it off your repo, you will have to delete it from your project locally and push up this version (with the file removed):
`git rm config.env`

Then you can add it back into your project locally.

**Comment by oliverjam** [comment]
We've removed the `config.env` file, but now Travis throws errors because `env2` requires a `config.env`.

None of our tests are calling the database so we're not sure why Travis needs the config file, but we can't really merge without it right now.
