### ISSUE TITLE
Light styling

### ISSUE THREAD

**Issue by yvonne-liu** [pbywater/week6-zapo#46]
`Name, Ingredients, Cuisine` could be just slightly different text style so it's easier to differentiate ⭐️

**Comment by oliverjam** [comment]
Like we had time for CSS 🕙

**Comment by yvonne-liu** [comment]
🤷‍♀️ Isn't it like your favorite thing to do tho 🤷‍♂️

**Comment by yvonne-liu** [comment]
Keyword _light_ styling bruh

**Comment by oliverjam** [comment]
Happy now @yvonne-liu ?

**Comment by yvonne-liu** [comment]
:clap: so beautiful 👍
